
import Header from '@/components/Header'
import { Poppins } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import '../app/global.css'

const poppins = Poppins({
    weight: ['400', '700'],
    variable: '--font-poppins',
    subsets: ['latin'] 
  })

export const metadata = {
  title: 'Aprendendo NEXT',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={poppins.className}>
          
          <Header />
          {children}        
        
       
      </body>
    </html>
  )
}
