import Link from 'next/link'
import './globals.css'
import 'bootstrap/dist/css/bootstrap.min.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({ weight: ['400', '700'], subsets: ['latin'] })

export const metadata = {
  title: 'Front-End Insights',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={poppins.className}>
        <div className="navbar flex min-h-screen flex-col items-center justify-between max-w-5xl mx-auto">
          <header className="header flex items-center justify-between w-full py-10">
            <span className="text-2xl font-black cursor-default">INSIGHTS</span>
            <nav className="flex gap-10">
              <Link href="/">início</Link>
              <Link href="/products">Produtos</Link>
              <Link href="/cart">Carrinho</Link>
            </nav>
          </header>
        </div>
        {children}
        <footer className="p-10">
            <p>Feito com Next.js 13.4</p>
          </footer>
      </body>
    </html>
  )
}
