
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Home(){
  return (
    <>
      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Sint error consectetur modi odio obcaecati tempore dignissimos assumenda, eum reiciendis dolores magni autem at debitis voluptas. Rem ipsa deleniti autem dignissimos.
        </p>
      </main>

    </>
    
  )
}

